# Generated by Django 6.0.5 on 2026-05-17 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('business_goal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('enrichment_data', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('personalized_email', models.TextField(blank=True)),
                ('sheets_row_id', models.CharField(blank=True, max_length=255)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['company_name'], name='leads_lead_company_6c0418_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('drive_file_url', models.URLField(blank=True)),
                ('report_content', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='leads.lead')),
            ],
        ),
    ]
